version: "3.8"
services:
  web:
    build:
      context: ./
      dockerfile: Dockerfile.app
      target: runner
    volumes:
      - .:/app
    command: npm run dev
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development

  # storybook:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile.storybook
  #   ports:
  #     - "6006:6006"
  #   volumes:
  #     - .:/app
  #     - /app/node_modules
